# Generated by Django 4.1.7 on 2023-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ism', models.CharField(max_length=256)),
                ('Familiya', models.CharField(max_length=256)),
                ('yoshi', models.IntegerField(null=True)),
                ('city', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Farg`ona', 'Farg`ona'), ('Namangan', 'Namangan'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxandaryo', 'Surxandaryo'), ('Buxoro', 'Buxoro'), ('Samarqand', 'Samarqand'), ('Jizzax', 'Jizzax'), ('Navoiy', 'Navoiy'), ('Sirdaryo', 'Sirdaryo'), ('Xorazm', 'Xorazm')], max_length=125, null=True)),
            ],
        ),
    ]
