# Generated by Django 4.1.7 on 2023-06-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_subscribe_delete_user_remove_contact_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='emal',
            new_name='email',
        ),
    ]
